[package]
name = "ai-portfolio-types"
edition.workspace = true
version.workspace = true
authors.workspace = true
rust-version.workspace = true
repository.workspace = true

[dependencies]
serde = { workspace = true }
cosmwasm-std = { workspace = true }
anyhow = { workspace = true }
