version: "3"

dotenv: [".env"]

includes:
  contracts: ./taskfile/contracts.yml
  components: ./taskfile/components.yml
  backend: ./taskfile/backend.yml
  deploy: ./taskfile/deploy.yml
  test: ./taskfile/test.yml

tasks:
  default:
    cmds:
      - task --list-all

  lint:
    desc: "Run code formatting and linting checks"
    cmds:
      - cargo fmt --all -- --check
      - cargo fix --allow-dirty --allow-staged
      - cargo clippy --all-targets -- -D warnings

  download-wit:
    vars:
      BRANCH: '{{.BRANCH | default "main"}}'
    cmds:
      - |
        # Create a temporary directory
        rm -rf temp_clone
        mkdir temp_clone

        # Clone the specific branch into the temp directory
        git -C temp_clone clone --depth=1 --branch {{.BRANCH}} --single-branch https://github.com/Lay3rLabs/wavs-wasi.git

        # Clear existing content and create wit directory
        rm -rf wit
        mkdir -p wit

        # Copy it over
        cp -r temp_clone/wavs-wasi/wit-definitions/* wit/

      # Fetch deps
      - cd wit/operator && wkg wit fetch
      - cd wit/aggregator && wkg wit fetch
      - cd wit/types && wkg wit fetch

        # Clean up
      - defer: rm -rf temp_clone
