[package]
name = "ai-portfolio-utils"
version.workspace = true
edition.workspace = true
authors.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = []
multitest = ["dep:cw-multi-test"]
on-chain = ["dep:deadpool", "dep:tokio", "dep:reqwest", "dep:toml"]

[dependencies]
vault = { workspace = true }
serde = { workspace = true }
cosmwasm-std = { workspace = true }
layer-climb = { workspace = true }
tracing = { workspace = true }
cfg-if = { workspace = true }
tracing-subscriber = { workspace = true }
anyhow = { workspace = true }
wavs-types = { workspace = true }
toml = { workspace = true, optional = true }
reqwest = { workspace = true, optional = true }
tokio = { workspace = true, optional = true }
deadpool = { workspace = true, optional = true }
cw-multi-test = { workspace = true, optional = true }
